docker cp  mysql:/var/lib/mysql  /mydata/mysql/data
docker cp  mysql:/etc/mysql /mydata/mysql/conf
docker cp  mysql:/var/log/mysql /mydata/mysql/log
docker cp  redis:/data /mydata/redis/data
docker cp  nginx:/etc/nginx /mydata/nginx/conf
docker cp  nginx:/usr/share/nginx/html /mydata/nginx/html
docker cp  nginx:/var/log/nginx /mydata/nginx/logs
docker cp  rabbitmq:/var/lib/rabbitmq /mydata/rabbitmq/data
docker cp  elasticsearch:/usr/share/elasticsearch/plugins /mydata/elasticsearch/plugins
docker cp  elasticsearch:/usr/share/elasticsearch/data /mydata/elasticsearch/data
docker cp  logstash:/usr/share/logstash/pipeline/logstash.conf /mydata/logstash/logstash.conf
docker cp  mongo:/data/db /mydata/mongo/db
docker cp  minio:/data /mydata/minio/data
